version: 0.0
os: windows
files:
  - source: /
    destination: C:\app
hooks:
  BeforeInstall:
    - location: scripts\before_install.ps1
  AfterInstall:
    - location: scripts\after_install.ps1
  ApplicationStart:
    - location: scripts\start_app.ps1
